### ISSUE TITLE
Check doi syntax before the command appears in a context menu

### ISSUE THREAD

**Issue by crazytexer** [mdmower/doi-resolver-chrome#9]
Thank you very much for this Chrome extension! It is very useful for scientific research and writing.

May I suggest you to make a slight improvement? In my opinion, the `Resolve DOI` command in the context menu should not be visible for a selection of _any_ text. It should be visible only in case the selection matches the basic DOI syntax, i.e., it starts with `10.` and contains `/`. You may also want to allow the shortDOI match: for that, the selection should start with `10/`. When checking the syntax in both cases, the leading and trailing whitespace characters in the selection should be ignored.

**Comment by mdmower** [comment]
Thanks for the report @crazytexer . I got this working as you describe back in 2011 ([thanks StackOverflow](https://stackoverflow.com/questions/4730843/how-do-i-restrict-context-menus-to-appear-only-for-certain-selected-text-in-a-ch)), but apparently that method stopped working with a recent Chrome release. I'll see if I can get this fixed up.

**Comment by mdmower** [comment]
I remember this feature a bit better now. I originally opted not to implement it because it requires permission for the extension to access the web page in order to inspect the selected text. I've tried my best to keep required permissions at a minimum, so this is being introduced as an optional feature:

![image](https://user-images.githubusercontent.com/264920/128618893-b750ef82-0559-4aa9-9bb6-9b9c53b3c582.png)

The updated extension (version 4.1.0) is pending review by Google and I expect it will be published in the next day or two.

**Comment by mdmower** [comment]
Feature is published. Closing issue. Please let me know if any problems are noticed with it.
